const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
  SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
  SET_RECENT_SONG: "SET_RECENT_SONG",
  SEARCH: "SEARCH",

  //music:
  PLAY: "PLAY",
  PLAYLIST: "PLAYLIST",
  LOADING: "LOADING",
  ZERO_SCROLL_TOP: "ZERO_SCROLL_TOP",
};

export default actionTypes;
